AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - spec/support/**/*
plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - 'lib/gruf-commander.rb'

####################################################################################################
# RSpec Configurations
####################################################################################################

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 15

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 50

RSpec/AnyInstance:
  Enabled: false

# This does not work with RPC messages
RSpec/VerifiedDoubles:
  Enabled: false
